[tool.poetry]
name = "aurora-platform"
version = "0.1.0"
description = "Plataforma Aurora Core"
authors = ["Equipe Aurora <dev@aurora.com>"]

[[tool.poetry.packages]]
include = "aurora"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
pydantic = {extras = ["email"], version = "^2.7.1"}
dynaconf = "^3.2.5"
sqlalchemy = "^2.0.30"
alembic = "^1.13.1"
psycopg2-binary = "^2.9.9"
python-dotenv = "^1.0.1"
redis = "^5.0.4"
pyyaml = "^6.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
httpx = "^0.27.0"
pytest-cov = "^5.0.0"
flake8 = "^7.0.0"

[tool.poetry.scripts]
aurora = "aurora.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.main:api"
