[tool.poetry]
name = "aurora-platform"
version = "0.1.0"
# ... outras configurações ...

[tool.poetry.dependencies]
python = "^3.10"
# ... suas dependências ...

[tool.poetry.dev-dependencies]
alembic = "^1.13.1"

# Adicione esta seção CRUCIAL
[tool.poetry.build]
generate-setup-file = false
script = "build.py"