"""Cria a tabela inicial de clientes

Revision ID: cc5588aecd7e
Revises:
Create Date: 2025-06-19 22:58:18.957685

"""

from typing import Sequence, Union

# from alembic import op # Removido por não ser usado
# import sqlalchemy as sa # Removido por não ser usado


# revision identifiers, used by Alembic.
revision: str = "cc5588aecd7e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
