name: Security Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente aos domingos

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          
      - name: Run Bandit (Static Application Security Testing)
        run: |
          poetry run bandit -r src/ -f json -o bandit-results.json
        continue-on-error: false
          
      - name: Check for vulnerabilities in dependencies
        run: |
          # Export dependencies to a requirements.txt file for safety check
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          poetry run safety check -r requirements.txt --json > safety-results.json
        continue-on-error: false
          
      - name: Run tests with coverage
        run: |
          pytest --cov=src tests/ --cov-report=xml
          
      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            bandit-results.json
            safety-results.json
            coverage.xml
            
      - name: Check for secrets in code
        uses: zricethezav/gitleaks-action@master
        continue-on-error: false
        
      - name: Start application for ZAP Scan
        run: |
          poetry run uvicorn src.aurora_platform.main:app --host 0.0.0.0 --port 8000 &
          sleep 5 # Give the server time to start

      - name: Run OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: 'http://localhost:8000/openapi.json'
          docker_name: 'owasp/zap2docker-stable'
          format: 'json'
          cmd_options: '-a'
          fail_action: true
        continue-on-error: false
        
      - name: Generate security report
        run: |
          echo "# Security Scan Report" > security-report.md
          echo "## Dependency Vulnerabilities" >> security-report.md
          python -c "import json; data = json.load(open('safety-results.json')); print(f'Found {len(data)} vulnerabilities' if isinstance(data, list) else 'No vulnerabilities found')" >> security-report.md
          echo "## Code Security Issues" >> security-report.md
          python -c "import json; data = json.load(open('bandit-results.json')); print(f'Found {len(data.get(\"results\", []))} issues' if isinstance(data, dict) and 'results' in data else 'No issues found')" >> security-report.md
          echo "## Test Coverage" >> security-report.md
          python -c "import xml.etree.ElementTree as ET; root = ET.parse('coverage.xml').getroot(); print(f'Coverage: {root.attrib.get(\"line-rate\", 0) * 100:.2f}%')" >> security-report.md
          
      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security-report.md

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t aurora-platform:latest .

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL' # Fail on high and critical vulnerabilities